{{ if .Values.db.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stride-db
spec:
  selector:
    matchLabels:
      app: stride-db
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: stride-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: db
        image: {{ .Values.db.image | quote }}
        args:
          - -c
          - max_wal_size=10GB
          - -c
          - min_wal_size=1GB
        resources: {{ .Values.db.resources }}
        env:
        - name: POSTGRES_PASSWORD
          valueFrom: {"secretKeyRef":{"name":"db", "key":"POSTGRES_PASSWORD"}}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: stride_db
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: data
        nfs:
          server: {{ .Values.db.nfsServer | quote }}
          path: {{ .Values.db.nfsPath | quote }}
      - name: dshm
        emptyDir:
            medium: Memory
{{ end }}