{{ if .Values.db.enabled }}
{{ if .Values.db.nodePort }}
apiVersion: v1
kind: Service
metadata:
  name: stride-db-nodeport
spec:
  type: NodePort
  selector:
    app: stride-db
  ports:
  - name: "5432"
    port: 5432
    nodePort: {{  .Values.db.nodePort }}
{{ end }}
{{ end }}