apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmon
spec:
  selector:
    matchLabels:
      app: webmon
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webmon
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: webmon
        # built from ../webmon
        image: ghcr.io/orihoch/hasadna-open-bus-webmon:be9f0b02da27ad46808fa7cf516c5dca7144d6c1
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom: { "secretKeyRef": { "name": "siri-requester", "key": "OPEN_BUS_S3_ACCESS_KEY_ID" } }
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom: { "secretKeyRef": { "name": "siri-requester", "key": "OPEN_BUS_S3_SECRET_ACCESS_KEY" } }
          - name: BUCKET_NAME
            valueFrom: { "secretKeyRef": { "name": "siri-requester", "key": "OPEN_BUS_S3_BUCKET" } }
