odata:
  lint-environments: odata-kamatera
  automatic-update:
    commit-message: automatic update of odata-ckan
    namespace-name: odata
    deployment-name: ckan
    container-name: ckan
    image-prop: ckanImage
    kubeconfig: .rancher.kubeconfig

avidcovider:
  lint-environments: avidcovider-gcloud
  automatic-updates:
    - commit-message: automatic update of avid-covider pipelines
      namespace-name: avidcovider
      deployment-name: pipelines
      container-name: pipelines
      image-prop: pipelinesImage

datacity:
  lint-environments: datacity
  automatic-updates:
    - commit-message: automatic update of datacity ckan dgp server
      namespace-name: datacity
      deployment-name: ckan-dgp
      container-name: server
      image-prop: ckanDgpServerImage
      kubeconfig: .rancher.kubeconfig
    - commit-message: automatic update of datacity dgp importer
      namespace-name: datacity
      deployment-name: importer
      container-name: importer
      image-prop: dgpAppImage
      kubeconfig: .rancher.kubeconfig

redash:
  lint-environments: redash
