avidcovider:
  pipelinesImage: docker.pkg.github.com/hasadna/avid-covider-pipelines/pipelines:a32a5293d45c588859b28e8ecebcf4c7d1180cef
datacity:
  ckanDgpServerImage: docker.pkg.github.com/hasadna/datacity-ckan-dgp/server:4a61be492e5c72e56d3aa9caadee5315cd48f90b
  dgpAppDbImage: akariv/dgp-app-db@sha256:8ebf03009fb6c6e42308c2579b4ac2d979325a492fffd5942af0de3fc709ce28
  dgpAppImage: docker.pkg.github.com/hasadna/datacity-dgp-importer/server:4390a988da6a1f00972fd9be762b2afc20ce0d37
mysadna:
  image: uumpa/hasadna-mysadna:c0a681d5a0c68ada76b6d68fce1c2115224790a9
odata:
  ckanImage: ghcr.io/orihoch/data4dappl/odata-ckan:a00ae4862a3a92d51334aa4e2d441e20bbf368f9
oknesset:
  DataBackendImage: uumpa/knesset-data-backend:bc03d3c1830a856d6bbacf4b2481d83dd1f836c6
  WebUiImage: uumpa/knesset-data-web-ui:94b6de1cc89ae20647e35aa606c3c9b95e81dbe6
openpension:
  client:
    image: hasadna/open-pension-client:1f8f83e2a8e61e0928e4b5f499475f8e675265bd
  server:
    image: uumpa/hasadna-openpension:server-c72f525ec4d7de2e4337c0a7b0b1f6f8d357b72f
