apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# copied from https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.3/manifests/install.yaml
# commented argocd-cm, argocd-notifications-cm, argocd-rbac-cm, argocd-tls-certs-cm configmaps (which were manually modified)
- install.yaml

patchesStrategicMerge:
- argocd-server-deployment.yaml
- argocd-repo-server-deploy.yaml
# needs to be applied manually to existing argocd-cm
# - argocd-cm.yaml
