apiVersion: v1
kind: ConfigMap
metadata:
  name: gtfs-nginx
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location / {
        index null;
        root /srv/;
        autoindex on;
      }
    }
