kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odata-minikube-ckan-kubectl
  namespace: odata-minikube
rules:
- apiGroups: [""]
  resources: [secrets]
  verbs: [get, create]
- apiGroups: [""]
  resources: [pods]
  verbs: [list, get]
- apiGroups: [""]
  resources: [pods/exec]
  verbs: [create]
- apiGroups: [""]
  resources: [pods/portforward]
  verbs: [create]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odata-minikube-ckan-kubectl
  namespace: odata-minikube
subjects:
- kind: ServiceAccount
  name: odata-minikube-ckan-kubectl
roleRef:
  kind: Role
  name: odata-minikube-ckan-kubectl
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: odata-minikube-ckan-kubectl
  namespace: odata-minikube
