{{ if and .Values.enabled .Values.enableLogs }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bindplane-log-agent
spec:
  selector:
    matchLabels:
      name: bindplane-log-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: bindplane-log-agent
    spec:
      serviceAccountName: default
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - image: docker.io/bluemedora/bindplane-log-agent:latest
          imagePullPolicy: Always
          name: bindplane-log-agent
          resources:
            limits:
              memory: "250Mi"
              cpu: 250m
            requests:
              memory: "250Mi"
              cpu: 100m
          volumeMounts:
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
          env:
            - name: AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: COMPANY_ID
              valueFrom:
                secretKeyRef:
                  name: bindplane-logs
                  key: COMPANY_ID
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bindplane-logs
                  key: SECRET_KEY
            - name: TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: bindplane-logs
                  key: TEMPLATE_ID
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
{{ end }}