openbus:
  enabled: true
  nfsServer: "172.16.0.9"
  sshTunnelSecretName: sshtunnel

  # siriRequesterPauseForDebug: true
  siriRequesterResources: '{"requests": {"cpu": "200m", "memory": "1000Mi"}, "limits": {"memory": "1500Mi"}}'
  siriRequesterNginxResources: '{"requests": {"cpu": "50m", "memory": "100Mi"}, "limits": {"memory": "200Mi"}}'
  siriRequesterNfsPath: "/openbus/siri-requester"
  siriRequesterSecretName: siri-requester

  siriEtlProcessNewSnapshotsResources: '{"requests": {"cpu": "600m", "memory": "5000Mi"}, "limits": {"memory": "8000Mi"}}'

  db:
    image: "postgres:13"
    resources: '{"requests": {"cpu": "4000m", "memory": "16000Mi"}, "limits": {"cpu": "4000m", "memory": "16000Mi"}}'
    nfsPath: "/openbus/stride-db"
    nodePort: 31834

  airflowHomeNfsPath: "/openbus/airflow-home"
  airflowDb:
    image: "postgres:13"
    resources: '{"requests": {"cpu": "50m", "memory": "300Mi"}, "limits": {"memory": "700Mi"}}'
    nfsPath: "/openbus/airflow-db"
  airflowWebserver:
    resources: '{"requests": {"cpu": "250m", "memory": "1000Mi"}, "limits": {"memory": "2000Mi"}}'
  airflowScheduler:
    resources: '{"requests": {"cpu": "600m", "memory": "8000Mi"}, "limits": {"memory": "12000Mi"}}'

  airflow:
    enableEmails: true
    AIRFLOW__SMTP__SMTP_MAIL_FROM: "Open Bus Airflow <open-bus-airflow@hasadna.org.il>"
    AIRFLOW__WEBSERVER__BASE_URL: "https://open-bus-airflow.hasadna.org.il"

  strideApiResources: {"requests": {"cpu": "1000m", "memory": "1000Mi"}, "limits": {"memory": "2000Mi"}}

  ingresses:
    - name: siri-requester
      ssl: true
      httpauth:
        # htpasswd -c auth USERNAME
        # kubectl -n openbus create secret generic siri-requester-httpauth --from-file=auth
        # rm -f auth
        secretName: "siri-requester-httpauth"
        message: "Authentication Required"
      rules:
        - host: open-bus-siri-requester.hasadna.org.il
          serviceName: siri-requester
          servicePort: 80
    - name: airflow-webserver
      ssl: true
      rules:
        - host: open-bus-airflow.hasadna.org.il
          serviceName: airflow-webserver
          servicePort: 8080
    - name: stride-api
      ssl: true
      rules:
        - host: open-bus-stride-api.hasadna.org.il
          serviceName: stride-api
          servicePort: 80
