apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: hello-world
        env:
          - name: aaa
            value: {{ .Values.aaa | quote }}
          - name: bbb
            value: {{ .Values.bbb | quote }}
