apps:
  - name: cluster-admin
    project: default
    destinationNamespace: default
    source:
      path: apps/cluster-admin
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: testing-argocd
      helm:
        valueFiles:
          - values-hasadna.yaml
