projects:

  - name: openbus
    spec:
      destinations:
        - name: '*'
          namespace: openbus
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'

  - name: betaknesset
    spec:
      destinations:
        - name: '*'
          namespace: betaknesset
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'

  - name: anyway
    spec:
      destinations:
        - name: '*'
          namespace: anyway
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: anyway-dev
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'

apps:

  - name: cluster-admin
    project: default
    destinationNamespace: default
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/cluster-admin
      helm:
        valueFiles:
          - values-hasadna.yaml

  - name: openbus
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/openbus
      helm:
        valueFiles:
          - values-hasadna.yaml
          - values-hasadna-auto-updated.yaml

  - name: betaknesset
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/betaknesset

  - name: anyway-prod
    project: anyway
    destinationNamespace: anyway
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/anyway
      helm:
        valueFiles:
          - values-anyway-prod.yaml
          - values-anyway-auto-updated.yaml

  - name: anyway-dev
    project: anyway
    destinationNamespace: anyway-dev
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/anyway
      helm:
        valueFiles:
          - values-anyway-dev.yaml
          - values-anyway-auto-updated.yaml
